[theme]
base = "light"
primaryColor = "#0F62FE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#161616"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

